//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkGorkogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Orrder = new HashSet<Orrder>();
        }
    
        public int IDClient { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronimic { get; set; }
        public string CodeClient { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> DataBirth { get; set; }
        public string Adress { get; set; }
        public string Mail { get; set; }
        public string PasswordClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orrder> Orrder { get; set; }
    }
}
